sudo: required

language: cpp

compiler:
  - gcc
  - clang

services:
  - docker

before_install:
- docker build -t ubuntu/gcc-5 .

script:
- docker run -t -e CXX=$CXX -v $TRAVIS_BUILD_DIR:/lz4_stream ubuntu/gcc-5
