language: cpp

sudo: false

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

before_script:
  - mkdir build
  - cd build
  - cmake -DENABLE_COVERAGE=ON ..
  - make

script:
  - ctest -V

after_success:
  - bash <(curl -s https://codecov.io/bash)
