sudo: required

language: c++

services:
  - docker

before_install:
- docker build -t ubuntu/gcc-5 .

script:
- >
  docker run -t -v $TRAVIS_BUILD_DIR:/lz4_stream ubuntu/gcc-5
  /bin/bash -c "cd /lz4_stream && scons && ./lz4_stream_test"
