clone_folder: c:\projects\lz4_stream

image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

install:
  - git submodule update --init --recursive


before_build:
  - cmd: |-
      mkdir build
      cd build
      cmake ..

build:
  project: c:\projects\lz4_stream\build\lz4_stream.sln

test_script:
  - ctest -V
